# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiplomProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiplomProject
  pod 'RealmSwift'
  pod 'DTTableViewManager'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

end
